# Generated by Django 4.0.3 on 2023-07-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='Salesperson',
            new_name='salesperson',
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='employee_id',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
