# Generated by Django 4.0.3 on 2023-07-26 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_options_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(default='INCOMPLETE', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='service_rest.status'),
            preserve_default=False,
        ),
    ]
